stages:
  - androidbuild
  - androidtest

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - evan                   # <-- change to your runner's tag
  before_script:                    # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Cycino/gradlew
  script:
    - cd Frontend/Cycino                   # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew build
  only:
    refs:
      - evan_CICD
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - evan                  # <-- change to your runner's tag
  before_script:                   # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Cycino/gradlew
  script:
    - cd Frontend/Cycino                  # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew test
  only:
    refs:
      - evan_CICD
    changes:
      - Frontend/**/*

